"""Mirror the WindowsTest RC3 chain for Light / SemiBold, leaving the original untouched.

The RC3 scripts in FridayFonts-WindowsTest resolve every input and output from
their own location (ROOT = parents[n]).  They are copied unchanged into a
sibling work tree, FridayFonts-WindowsTest-weights, except for the edits below:
each replaces a hard-coded Regular/Medium/Bold list with Light/SemiBold, or
points at the Light/SemiBold inputs.  Every edit asserts that it matched once,
so a change upstream fails here instead of silently running the old list.
"""
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / 'FridayFonts-WindowsTest'
WS = ROOT / 'FridayFonts-WindowsTest-weights'
NEW = "[('Light',300),('SemiBold',600)]"

EDITS = {
    'tools/font_raster.py': [],
    'tools/select_kanji_guard_caps.py': [
        ("for style in ['Regular','Medium','Bold']:", "for style in ['Light','SemiBold']:")],
    'tools/build_kanji_guard_trial.py': [
        ("        for style in ['Regular', 'Medium', 'Bold']:", "        for style in ['Light', 'SemiBold']:"),
        # The R/M/B faces each had 11457 hinted kanji; the count is per face now
        # and is checked against the grid trial's own manifest by build_weights.
        ("            assert len(selected) == 11457\n", "            assert len(selected) > 11000, len(selected)\n"),
        ("for s, w in [('Regular', 400), ('Medium', 500), ('Bold', 700)]) + '\\n')",
         "for s, w in [('Light', 300), ('SemiBold', 600)]) + '\\n')")],
    'tools/build_balance_trial.py': [
        ("    for style in ['Regular', 'Medium', 'Bold']:", "    for style in ['Light', 'SemiBold']:"),
        ("for s, w in [('Regular', 400), ('Medium', 500), ('Bold', 700)]) + '\\n')",
         "for s, w in [('Light', 300), ('SemiBold', 600)]) + '\\n')")],
    'tools/verify_guard_balance.py': [
        ("    for style in ['Regular','Medium','Bold']:", "    for style in ['Light','SemiBold']:"),
        ("names=[n for n in order if code(s,n)!=code(b,n)];assert len(names)==11457",
         "names=[n for n in order if code(s,n)!=code(b,n)];assert len(names)>11000,len(names)")],
    'tools/build_ui_trial.py': [
        ("STYLES=['Regular','Medium','Bold']", "STYLES=['Light','SemiBold']"),
        ("for s,w in zip(STYLES,[400,500,700]))", "for s,w in zip(STYLES,[300,600]))")],
    'windows-lab/tools/build_lab.py': [
        ("    'mono': ('Friday Mono v48', ROOT.parent / 'FridayFonts/dist-v48/ttf', 'FridayMono'),",
         "    'mono': ('Friday Mono v48', ROOT.parent / 'FridayFonts/scripts/build-weights/mono-v48', 'FridayMono'),"),
        ("STYLES = [('Regular', 400), ('Medium', 500), ('Bold', 700)]", "STYLES = " + NEW)],
    'windows-lab/tools/build_candidate.py': [
        ("choices=['Regular','Medium','Bold','all'],default='Regular'", "choices=['Light','SemiBold','all'],default='all'")],
    'windows-lab/tools/fix_mono_kana_candidate.py': [
        ("    for style,weight in [('Regular',400),('Medium',500),('Bold',700)]:", "    for style,weight in " + NEW + ":")],
    'windows-lab/tools/finish_lab.py': [],
    'windows-lab/tools/page.html': [],
    'shipping-audit/tools/build_rc1.py': [],
    'shipping-audit/tools/build_rc2.py': [],
    'shipping-audit/tools/build_rc3.py': [],
}


def main():
    for rel, edits in EDITS.items():
        text = (SRC / rel).read_text()
        for old, new in edits:
            assert text.count(old) == 1, (rel, old)
            text = text.replace(old, new)
        out = WS / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
    # Output folders the scripts write into without creating them.
    (WS / 'kanji-guard-trial-2.3').mkdir(exist_ok=True)
    shutil.copyfile(SRC / 'OFL.txt', WS / 'OFL.txt')
    shutil.copytree(SRC / 'licenses', WS / 'licenses', dirs_exist_ok=True)
    (WS / 'README.md').write_text(
        '# Light / SemiBold work tree\n\nGenerated by FridayFonts/scripts/weights/make_ws.py. '
        'Mirrors the FridayFonts-WindowsTest RC3 chain for the two new weights; '
        'nothing here is a release.\n')
    print('mirror ready:', WS)


if __name__ == '__main__':
    main()
